/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ImagePreview: typeof import('@varlet/ui')['ImagePreview']
  const StyleProvider: typeof import('@varlet/ui')['StyleProvider']
}
